đồ án/a/thuctap/Controllers/_clientNewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using thuctap.Models;
namespace thuctap.Controllers
{
    public class _clientNewController : Controller
    {
        // GET: _clientNew
        bangiayDataContext db = new bangiayDataContext();
        public ActionResult Index()
        {
            var news = from n in db.News
                       orderby n.ID descending
                       select n;
            return View(news);
        }
        public ActionResult NewDetail()
        {
            int key = Convert.ToInt32(Request["key"]);
            var news = from n in db.News
                       where n.ID == key
                       select n;
            return View(news);
        }
    }
}

đồ án/a/thuctap/Views/_clientNew/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/client.cshtml";
}



<div style="margin-bottom:50px">
    <r style="font-size: 30px; font-weight: bolder; color: red">Tin tức công nghệ!</r>
</div>
<hr />
@foreach (var item in Model)
{
    <div class="row">
        <div class="col-1"></div>
        <div class="col-3">
            <a href="/_clientNew/NewDetail?key=@item.ID"><img src="@item.Image" width="250" height="250" style="border:5px solid #e0e0e0" /></a>
        </div>
        <div class="col">
            <a href="/_clientNew/NewDetail?key=@item.ID" style="font-size: 28px; font-weight: bolder; color:black">@item.Title !</a>
        </div>
        <div class="col-1"></div>
    </div>
    <hr />
}
@*<div class="row">
    <div class="col-5"></div>
    <div class="col">
        <div class="paginate">
            @Html.PagedListPager(Model, page => Url.Action("Index", "_clientNew", new { page }))
        </div>
    </div>
    <div class="col-5"></div>
</div>*@

đồ án/a/thuctap/Views/_clientNew/NewDetail.cshtml
@{
    ViewBag.Title = "NewDetail";
    Layout = "~/Views/Shared/client.cshtml";
}


<div style="margin-bottom:50px;text-align:center">
    <a href="Index" style="font-size: 35px;text-align:center; font-weight: bolder">Tin tức: </a>
    @foreach (var item in Model)
    {
        <r style="font-size: 30px;text-align:center; font-weight: bolder; color: black">@item.Title!</r>
    }
</div>
<hr />
@foreach (var item in Model)
{
    <div class="container">
        <div class="row" style="text-align:center">
            <a style="margin-left:14%;margin-bottom:30px;margin-top:30px"><img src="@item.Image" width="800" height="500" /></a>
        </div>
        <div class="row">
            @{
                string myEncodedString = HttpUtility.HtmlEncode(@item.Content);
            }
            <a style="font-size: 20px; color:black">@Html.Raw(HttpUtility.HtmlDecode(@item.Content))</a>
        </div>
    </div>
    <hr />
}