đồ án/a/thuctap/Controllers/productController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using thuctap.Models;
using PagedList;

namespace thuctap.Controllers
{
    public class productController : Controller
    {
        // GET: product
        bangiayDataContext db = new bangiayDataContext();
        public ActionResult Index(int? page)
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var pro = from p in db.Products
                      select p;
            ViewBag.pro = pro;
            ViewBag.product = from b in db.Products
                              select b;
            return View(pro.ToPagedList(page ?? 1, 5));
        }
        [HttpPost]
        public ActionResult Index(int? page, FormCollection a)
        {
            string name = Request["key"];
            var pro = from p in db.Products
                      where p.Name.Contains(name)
                      select p;
            return View(pro.ToPagedList(page ?? 1, 5));
        }


        public ActionResult Create()
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            var pro = (from p in db.Products
                       orderby p.ID descending
                       select p).Take(3);
            ViewBag.brand = from p in db.Brands
                            select p;
            return View(pro);
        }
        [HttpPost]
        public ActionResult Create(Product pro)
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.date = DateTime.Now;
            Product test = db.Products.Where(p => p.Name == Request["Ten"]).FirstOrDefault();
            if (test != null)
            {
                ViewBag.test = "Sản phẩm " + Request["Ten"] + " đã tồn tại!";
            }
            else
            {
                pro.Name = Request["Ten"];
                pro.Description = Request["MoTa"];
                pro.Image = Request["Anh"];
                pro.Warranty = Request["Warr"];
                pro.ID_Brand = Convert.ToInt32(Request["ID_Hang"]);
                pro.Price = Convert.ToInt32(Request["Pri"]);
                pro.Promotion_Price = Convert.ToInt32(Request["Pro_Price"]);
                pro.created_at = ViewBag.date;
                db.Products.InsertOnSubmit(pro);
                db.SubmitChanges();
            }

            return this.Create();
        }


        public ActionResult Edit(int id)
        {
            var pro = db.Products.First(b => b.ID == id);
            ViewBag.brand = from p in db.Brands
                            select p;
            return View(pro);
        }
        [HttpPost]
        public ActionResult Edit(int id, Product pro)
        {
            ViewBag.date = DateTime.Now;
            pro = db.Products.Where(p => p.ID == id).SingleOrDefault();
            pro.Name = Request["Ten"];
            pro.Description = Request["MoTa"];
            pro.Warranty = Request["Warr"];
            pro.Image = Request["Anh"];
            pro.ID_Brand = Convert.ToInt32(Request["ID_Hang"]);
            pro.Price = Convert.ToDecimal(Request["Pri"]);
            pro.Promotion_Price = Convert.ToDecimal(Request["Pro_Price"]);
            pro.updated_at = ViewBag.date;
            UpdateModel(pro);
            db.SubmitChanges();
            return RedirectToAction("Index");

        }


        public ActionResult Delete(int id)
        {
            var pro = db.Products.Where(b => b.ID == id).SingleOrDefault();
            db.Products.DeleteOnSubmit(pro);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }


        public ActionResult Edit_cre(int id)
        {
            var pro = db.Products.First(b => b.ID == id);
            ViewBag.brand = from p in db.Brands
                            select p;
            return View(pro);
        }
        [HttpPost]
        public ActionResult Edit_cre(int id, Product pro)
        {
            ViewBag.date = DateTime.Now;
            pro = db.Products.Where(p => p.ID == id).SingleOrDefault();
            pro.Name = Request["Ten"];
            pro.Description = Request["MoTa"];
            pro.Warranty = Request["Warr"];
            pro.Image = Request["Anh"];
            pro.ID_Brand = Convert.ToInt32(Request["ID_Hang"]);
            pro.Price = Convert.ToDecimal(Request["Pri"]);
            pro.Promotion_Price = Convert.ToDecimal(Request["Pro_Price"]);
            pro.updated_at = ViewBag.date;
            UpdateModel(pro);
            db.SubmitChanges();
            return RedirectToAction("Create");

        }


        public ActionResult Delete_cre(int id)
        {
            var pro = db.Products.Where(b => b.ID == id).SingleOrDefault();
            db.Products.DeleteOnSubmit(pro);
            db.SubmitChanges();
            return RedirectToAction("Create");
        }
    }
}

đồ án/a/thuctap/Views/product/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/admin.cshtml";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form thêm sản phẩm</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title" style="text-align:center; width:100%">Form thêm sản phẩm</h3>
                </div>
                <form method="post" action="/product/Create">
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>Tên sản phẩm</th>
                                    <th>ID hãng</th>
                                    <th>Mô tả</th>
                                    <th>Giá gốc</th>
                                    <th>Giá khuyến mại</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="odd gradeX" align="center">
                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền tên sản phẩm" name="Ten">
                                    </td>
                                    <td>
                                        <input required="" type="text" name="ID_Hang" list="dl">
                                        <datalist id="dl">
                                            @foreach (var item in ViewBag.brand)
                                            {
                                                <option value="@item.ID">@item.Name</option>
                                            }
                                        </datalist>
                                    </td>
                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền mô tả" name="MoTa">
                                    </td>
                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền giá gốc" name="Pri">
                                    </td>
                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền giá KM" name="Pro_Price">
                                    </td>


                                </tr>
                            </tbody>
                            <thead>
                                <tr align="center">
                                    <th>Avatar</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="odd gradeX" align="center">
                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền link ảnh" name="Anh">
                                    </td>
                                </tr>
                            </tbody>
                            <thead>
                                <tr align="center">
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="odd gradeX" align="center">
                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền thời hạn bảo hành" name="Warr">
                                    </td>
                                    <td style="text-align:center">
                                        <button type="submit" class="btn btn-primary">Thêm</button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </form>
                <h3 style="text-align:center; color:red">@ViewBag.test</h3>
            </div>

            <!-- /.card -->
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header" style="background-color:sandybrown">
                    <h3 class="card-title" style=" text-align:center; width:100%">Thông tin 3 sản phẩm được thêm gần nhất</h3>
                </div>
                <div class="card-body">
                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr align="center">
                                <th>Tên</th>
                                <th>ID hãng</th>
                                <th>Mô tả</th>
                                <th>Giá gốc</th>
                                <th>Giá khuyến mại</th>
                                <th>Avatar</th>
                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr class="odd gradeX" align="center">
                                    <td>@item.Name</td>
                                    <td>@item.ID_Brand</td>
                                    <td>@item.Description</td>
                                    <td>@string.Format("{0:#,##0}", @item.Price)đ</td>
                                    <td>@string.Format("{0:#,##0}", @item.Promotion_Price)đ</td>
                                    <td><img src="@item.Image" width="100" height="100" /></td>
                                    <td>
                                        @Html.ActionLink("Sửa", "Edit_cre", new { id = item.ID })
                                        @*<i class="fa fa-trash-o" fa-fw></i>@Html.ActionLink("Sửa", "Edit_cre", new { id = item.ID })
                                            <i class="fa fa-pencil fa-fw"></i>@Html.ActionLink("Xóa", "Delete_cre", new { id = item.ID })*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                    @*<select name="a">
                            @foreach (var item in Model)
                            {

                                <option value="@item.ID">@item.Name</option>
                            }
                        </select>*@
                </div>
            </div>
        </div>
    </div>
</div>

đồ án/a/thuctap/Views/product/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/admin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form sửa thông tin sản phẩm</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title" style="text-align:center; width:100%">Form sửa thông tin sản phẩm</h3>
                </div>
                <form role="form" method="post" action="/product/Edit/@Model.ID"
                      enctype="multipart/form-data">
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>Tên sản phẩm</th>
                                    <th>ID hãng</th>
                                    <th>Mô tả</th>
                                    <th>Giá gốc</th>
                                    <th>Giá khuyến mại</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="odd gradeX" align="center">
                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền tên sản phẩm"
                                               name="Ten" value="@Model.Name">
                                    </td>
                                    <td>
                                        <input required="" type="text" name="ID_Hang" value="@Model.ID_Brand" list="dl">
                                        <datalist id="dl">
                                            @foreach (var item in ViewBag.brand)
                                            {
                                                <option value="@item.ID">@item.Name</option>
                                            }
                                        </datalist>
                                    </td>

                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền mô tả"
                                               name="MoTa" value="@Model.Description">
                                    </td>
                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền giá gốc"
                                               name="Pri" value="@Model.Price">
                                    </td>
                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền giá KM"
                                               name="Pro_Price" value="@Model.Promotion_Price">
                                    </td>
                                </tr>
                            </tbody>
                            <thead>
                                <tr align="center">
                                    <th>Avatar</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="odd gradeX" align="center">
                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền link ảnh"
                                               name="Anh" value="@Model.Image">
                                    </td>
                                </tr>
                            </tbody>
                            <thead>
                                <tr align="center">
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="odd gradeX" align="center">
                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền thời hạn bảo hành"
                                               name="Warr" value="@Model.Warranty">
                                    </td>
                                    <td style="text-align:center">
                                        <button type="submit" class="btn btn-primary">Sửa</button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>

đồ án/a/thuctap/Views/product/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/admin.cshtml";
}
@*@using PagedList;
@using PagedList.Mvc;
@model IPagedList<thuctap.Models.Product>*@
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Sản phẩm</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Sản phẩm</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

@*<form class="form-inline ml-3" method="post" action="/product/Index">
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="searchbar">
                <input class="search_input" type="text" name="key" placeholder="Tìm kiếm">
                <button type="submit" class="btn btn-primary" style="background-color:white; border-color:white; color:blue">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</form>
<br>*@

<!-- Main content -->
<section class="content">
    <div class="card-body pad">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title" style="text-align:center; width:100%">Bảng sản phẩm</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="table" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tên</th>
                                    <th>ID hãng</th>
                                    <th>Mô tả</th>
                                    <th>Giá gốc</th>
                                    <th>Giá khuyến mại</th>
                                    <th>Avatar</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in ViewBag.pro)
                                {
                                    <tr class="odd gradeX" align="center">
                                        <td>@item.ID</td>
                                        <td>@item.Name</td>
                                        <td>@item.ID_Brand</td>
                                        <td>@item.Description</td>
                                        <td>@string.Format("{0:#,##0}", @item.Price)đ</td>
                                        <td>@string.Format("{0:#,##0}", @item.Promotion_Price)đ</td>
                                        <td><img src="@item.Image" width="70" height="70" /></td>
                                        <td>
                                            @Html.ActionLink("Sửa", "Edit", new { id = item.ID })
                                            @*<i class="fa fa-trash-o" fa-fw></i>@Html.ActionLink("Sửa", "Edit", new { id = item.ID })
                                                <i class="fa fa-pencil fa-fw"></i>@Html.ActionLink("Xóa", "Delete", new { id = item.ID })*@
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tên</th>
                                    <th>ID hãng</th>
                                    <th>Mô tả</th>
                                    <th>Giá gốc</th>
                                    <th>Giá khuyến mại</th>
                                    <th>Avatar</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                        @*<div style="margin-left: 50%;" class="paginate">
                                @Html.PagedListPager(Model, page => Url.Action("Index", "product", new { page }))
                            </div>*@

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>